//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHang.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Order
    {
        public int Id { get; set; }

        [Display(Name = "Tên đơn hàng")]
        public string Name { get; set; }

        [Display(Name = "Mã người mua")]
        public Nullable<int> UsertId { get; set; }

        [Display(Name = "Trạng thái")]
        public Nullable<int> Status { get; set; }

        [Display(Name = "Ngày tạo")]
        public Nullable<System.DateTime> CreatedOnUtc { get; set; }
    }
}
